name: Clone Repos to Current Org

on:
  workflow_dispatch:

jobs:
  clone_repos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install GitHub CLI and Git
        run: |
          sudo apt-get update
          sudo apt-get install gh git -y

      - name: Set Variables
        id: vars
        run: |
          CURRENT_ORG="${{ github.repository_owner }}"
          SOURCE_ORG="${CURRENT_ORG#org-echo-}"

          echo "SOURCE_ORG=$SOURCE_ORG" >> $GITHUB_ENV
          echo "TARGET_ORG=$CURRENT_ORG" >> $GITHUB_ENV

      - name: Clone and mirror repositories to inferred target org
        run: |
          mkdir -p cloned-repos
          cd cloned-repos

          gh repo list $SOURCE_ORG --json name -q '.[].name' | while read repo; do
            echo "Cloning $repo from $SOURCE_ORG"
            git clone "https://github.com/$SOURCE_ORG/$repo.git" "$repo"
            cd $repo

            git remote set-url origin "https://github.com/$TARGET_ORG/$repo.git"
            echo "Pushing $repo to $TARGET_ORG"

            git config http.extraheader "AUTHORIZATION: Basic $(echo -n x-access-token:${{ secrets.GITHUB_TOKEN }} | base64 --wrap=0)"
            git push --mirror
            cd ..
            rm -rf $repo
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
